services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newsdb
      MYSQL_USER: newsuser
      MYSQL_PASSWORD: newpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: newsuser
      DB_PASSWORD: newpassword
      DB_NAME: newsdb
      USE_DOCKER: "true" # Set USE_DOCKER for Docker environment
